apiVersion: v1
kind: Service
metadata:
  name: go-web-app
spec:
  selector:
    app: webapp
  ports:
  - port: 80 # we exposed this internally in k8s 
    targetPort: 8080 #application is running on this port 
