name: CI 
# If on changes on readme file or helm charts ignore the build trigger, because for helm chart changes argo cd will watch that 
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'helm/**'

jobs:
  
  build:  #This is the build step of the golang and running the unit test cases
   runs-on: ubuntu-latest

   steps:
     - name: checkout repository
       uses: actions/checkout@v4

     - name: Set up golang 1.22
       uses: actions/setup-go@v5

     - name: build
       uses: go build -o go-web-app
      
     - name: Test
       uses: go test ./..
      
  code-quality:  # Here doing the sonarqube 
    runs-on: ubuntu-latest

    steps: 
    - name: checkout repository
      uses: actions/checkout@v4

    - name: run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.56.2
    
  push:  # Now pushing the image to docker hub
    runs-on: ubuntu-latest

    needs: build  # For this build step to execute we are defining that build step should already be done before this step
    
    steps:
     - name: checkout repository
       uses: actions/checkout@v4
     
     - name: Set up docker build 
       uses: docker/setup-buildx-action@v3

     - name: Login to dockerhub
       uses: docker/login-action@v3
       with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

     - name: Build and Push action
       uses: docker/build-push-action@v6
       with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{github.run_id}} #Renaming the image in this format

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-app-chart/values.yaml 

    - name: Commit and push changes
      run: |
        git config --global user.email "adas6392@gmail.com"
        git config --global user.name "amit6392"
        git add helm/go-web-app-chart/values.yaml
        git commit -m "Update tag in Helm chart"
        git push